# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsview.ui'
#
# Created: Mon Mar 06 15:53:05 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SettingsView(object):
    def setupUi(self, SettingsView):
        SettingsView.setObjectName("SettingsView")
        SettingsView.resize(638, 354)
        self.centralWidget = QtGui.QWidget(SettingsView)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 311, 271))
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 70, 16))
        self.label_6.setObjectName("label_6")
        self.startModeBox = QtGui.QComboBox(self.groupBox)
        self.startModeBox.setGeometry(QtCore.QRect(100, 200, 191, 22))
        self.startModeBox.setObjectName("startModeBox")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_5.setObjectName("label_5")
        self.normalTempSlider = QtGui.QSlider(self.groupBox)
        self.normalTempSlider.setGeometry(QtCore.QRect(110, 110, 131, 22))
        self.normalTempSlider.setMinimum(800)
        self.normalTempSlider.setMaximum(9000)
        self.normalTempSlider.setPageStep(1000)
        self.normalTempSlider.setProperty("value", 5500)
        self.normalTempSlider.setOrientation(QtCore.Qt.Horizontal)
        self.normalTempSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.normalTempSlider.setObjectName("normalTempSlider")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 55, 16))
        self.label_3.setObjectName("label_3")
        self.longTxt = QtGui.QLineEdit(self.groupBox)
        self.longTxt.setGeometry(QtCore.QRect(100, 40, 51, 22))
        self.longTxt.setObjectName("longTxt")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 55, 16))
        self.label_4.setObjectName("label_4")
        self.latTxt = QtGui.QLineEdit(self.groupBox)
        self.latTxt.setGeometry(QtCore.QRect(100, 70, 51, 22))
        self.latTxt.setObjectName("latTxt")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.label_9.setObjectName("label_9")
        self.MaxTempN = QtGui.QSpinBox(self.groupBox)
        self.MaxTempN.setGeometry(QtCore.QRect(100, 140, 81, 22))
        self.MaxTempN.setMinimum(800)
        self.MaxTempN.setMaximum(10000)
        self.MaxTempN.setObjectName("MaxTempN")
        self.MinTempN = QtGui.QSpinBox(self.groupBox)
        self.MinTempN.setGeometry(QtCore.QRect(100, 170, 81, 22))
        self.MinTempN.setMinimum(800)
        self.MinTempN.setMaximum(9000)
        self.MinTempN.setObjectName("MinTempN")
        self.normalColorTmpLbl = QtGui.QLabel(self.groupBox)
        self.normalColorTmpLbl.setGeometry(QtCore.QRect(250, 110, 55, 16))
        self.normalColorTmpLbl.setObjectName("normalColorTmpLbl")
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 10, 281, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label.setObjectName("label")
        self.ModePathTxt = QtGui.QLineEdit(self.groupBox_2)
        self.ModePathTxt.setGeometry(QtCore.QRect(70, 20, 161, 22))
        self.ModePathTxt.setObjectName("ModePathTxt")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.label_7.setObjectName("label_7")
        self.LogFilePathTxt = QtGui.QLineEdit(self.groupBox_2)
        self.LogFilePathTxt.setGeometry(QtCore.QRect(70, 50, 161, 22))
        self.LogFilePathTxt.setObjectName("LogFilePathTxt")
        self.ApplyBtn = QtGui.QPushButton(self.centralWidget)
        self.ApplyBtn.setGeometry(QtCore.QRect(510, 250, 111, 28))
        self.ApplyBtn.setObjectName("ApplyBtn")
        self.CancelBtn = QtGui.QPushButton(self.centralWidget)
        self.CancelBtn.setGeometry(QtCore.QRect(380, 250, 111, 28))
        self.CancelBtn.setObjectName("CancelBtn")
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 110, 281, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.InfoLbl = QtGui.QLabel(self.groupBox_3)
        self.InfoLbl.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.InfoLbl.setTextFormat(QtCore.Qt.AutoText)
        self.InfoLbl.setScaledContents(False)
        self.InfoLbl.setWordWrap(True)
        self.InfoLbl.setObjectName("InfoLbl")

        self.retranslateUi(SettingsView)
        QtCore.QMetaObject.connectSlotsByName(SettingsView)

    def retranslateUi(self, SettingsView):
        SettingsView.setWindowTitle(QtGui.QApplication.translate("SettingsView", "SettingsView", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SettingsView", "Basis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SettingsView", "Start Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SettingsView", "Normal Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SettingsView", "Coordintates", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SettingsView", "Long:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SettingsView", "Lat:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("SettingsView", "Max Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("SettingsView", "Min Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.normalColorTmpLbl.setText(QtGui.QApplication.translate("SettingsView", "5500K", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SettingsView", "Power User", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SettingsView", "Modes ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SettingsView", "Log ", None, QtGui.QApplication.UnicodeUTF8))
        self.ApplyBtn.setText(QtGui.QApplication.translate("SettingsView", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.CancelBtn.setText(QtGui.QApplication.translate("SettingsView", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SettingsView", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.InfoLbl.setText(QtGui.QApplication.translate("SettingsView", "Remember you are updating only your personal user settings.", None, QtGui.QApplication.UnicodeUTF8))

